version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - dupl
    - gosec

  disable:
    # Bruit stylistique inutile
    - wsl
    - whitespace
    - wsl_v5

    # Trop strict / académique
    - mnd
    - prealloc
    - unparam
    - goconst
    - misspell
