FROM golang:1.26.4 AS ci
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go test ./...

FROM golang:1.26.4-bookworm AS builder

ENV CGO_ENABLED=0

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o persistence ./cmd/persistence/main.go

FROM debian:bookworm-slim AS runtime

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/persistence /app/persistence
COPY --from=builder /app/config.yaml /app/config.yaml

ENTRYPOINT []
CMD ["./persistence"]
